services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      apt-get update && apt-get install -y default-libmysqlclient-dev build-essential
      pip install -r requirements.txt
    startCommand: gunicorn server.server.wsgi:application
